In [2]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full

full=first+second


# Sort full in descending order: full_sorted

full_sorted=sorted(full,reverse=True)

# Print out full_sorted

print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


In [4]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(...)
 |      S.__format__(format_spec) -> str
 |      
 |      Return a formatted version of S as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getatt

In [7]:
# string to experiment with: room
room = "poolhouse"

# Use upper() on room: room_up  

room_up = room.upper()

# Print out room and room_up

print(room)
print(room_up)


# Print out the number of o's in room

room.count("o")

poolhouse
POOLHOUSE


3

In [9]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0

print(areas.index(20.0))


# Print out how often 14.5 appears in areas

print(areas.count(14.5))

2
0


In [12]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size

areas.append(24.5)
areas.append(15.45)

# Print out areas

print(areas)

# Reverse the orders of the elements in areas

areas.reverse()

# Print out areas

print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


In [19]:
# Definition of radius
r = 0.43

# Import the math package
 
import math as m

# Calculate C
C = 2*m.pi*r

# Calculate A
A = m.pi*r**2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [25]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians
from math import pi

# Travel distance of Moon over 12 degrees. Store in dist.
phi=radians(12)
dist=r*phi

dist1=2*pi*r*12/360
# Print out dist
print(dist)
print(dist1)

40317.10572106901
40317.10572106901


In [2]:
height=[74 ,74 ,72 , 75, 73,70]
weight=[180,
 215,
 210,
 210,
 188,
 176]

# Import numpy
import numpy as np

# Create a Numpy array from height: 

np_height=np.array(height)


# Print out np_height

print(np_height)

# Convert np_height to m: 

np_height_m=np_height*0.0254


# Print np_height_m

print(np_height_m)

[74 74 72 75 73 70]
[ 1.8796  1.8796  1.8288  1.905   1.8542  1.778 ]


In [37]:

height=[74 ,74 ,72 , 75, 73,70]
weight=[180,
 215,
 210,
 210,
 188,
 176]


# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg

np_weight_kg=np.array(weight)*0.453592

# Calculate the BMI: 

bmi=np_weight_kg/np_height_m**2

# Print out bmi

print(bmi)

[ 23.11037639  27.60406069  28.48080465  26.24790956  24.80333518
  25.25309083]


In [44]:
# height and weight are available as a regular lists


# Calculate the BMI: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light=np.array(bmi>21)

# Print out light

print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[bmi>21]);print(bmi[light]);

[ True  True  True  True  True  True]
[ 23.11037639  27.60406069  28.48080465  26.24790956  24.80333518
  25.25309083]
[ 23.11037639  27.60406069  28.48080465  26.24790956  24.80333518
  25.25309083]


In [52]:
print(height+weight)
print(np_height_m+np_weight_kg)

[74, 74, 72, 75, 73, 70, 180, 215, 210, 210, 188, 176]
[ 83.52616   99.40188   97.08312   97.15932   87.129496  81.610192]


In [54]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [58]:
# height and weight are available as a regular lists

#  already contains code that imports numpy as np

# already Store height lists as numpy arrays:np_height

# Store weight  lists as numpy arrays
np_weight = np.array(weight)

# Print out the weight at index 5
print(np_weight[5])

# Print out sub-array of np_height: index 3 up to and including index 5
print(np_height[3:6])
print(np_height[-1])

176
[75 73 70]
70


In [63]:
np_height.shape

help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an
        object whose __array__ method returns an array, or any
        (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then
        the type will be determined as the minimum type required
        to hold the objects in the sequence.  This argument can only
        be used to 'upcast' the array.  For downcasting, use the
        .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy
        will only be made if __array__ returns a copy, if obj is a
        nested sequence, or if a copy is needed to satisfy any of the other
        requirements (`dtype`, `order`, etc.).

In [4]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D Numpy array from baseball: np_baseball

np_baseball=np.array(baseball)


# Print out the type of np_baseball

print(type(np_baseball))

# Print out the shape of np_baseball

print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [70]:
# Print out the 3th row of np_baseball

print(np_baseball[2,:])

# Select the entire second column of np_baseball: np_baseball_weight

np_baseball_weight=np_baseball[:,1]

print(np_baseball_weight)

# Print out height of 124th player

print(np_baseball[3,1])

[ 210.    98.5]
[  78.4  102.7   98.5   75.2]
75.2


In [5]:
# np_baseball is available


# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. 
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height.
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column.
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.6351460533
Correlation: [[ 1.          0.95865738]
 [ 0.95865738  1.        ]]


In [10]:
# heights and positions are available as lists
positions = ['GK', 'M', 'A', 'D','GK',
             'GK', 'M', 'A', 'D','M', 
             'A', 'D','GK', 'M', 'A',
             'D','M', 'A', 'D','GK'] 
heights = [191, 184, 185, 180,184,
           185, 180,185, 180,192,
           185, 184, 185, 180,184,
           185, 180,185, 180,191] 
# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: 

np_positions=np.array(positions)
np_heights=np.array(heights)



# Heights of the goalkeepers: 

gk_heights=np_heights[np_positions =='GK']





# Heights of the other players: other_heights

other_heights=np_heights[np_positions!='GK']


# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

print("goalkeepers :");print(np_positions[np_positions =='GK'])

# Print out the median height of other players. Replace 'None'
print ("Median height of other players: " + str(np.median(other_heights)))

print("other players: ");print(np_positions[np_positions !='GK'])

Median height of goalkeepers: 185.0
goalkeepers
['GK' 'GK' 'GK' 'GK' 'GK']
Median height of other players: 184.0
other players: 
['M' 'A' 'D' 'M' 'A' 'D' 'M' 'A' 'D' 'M' 'A' 'D' 'M' 'A' 'D']
